# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: kubefwd
    main: ./cmd/kubefwd/kubefwd.go
    binary: kubefwd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
      - -a
      - -v
    ldflags: -s -w -X main.Version={{.Version}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

# Sign release artifacts with Cosign (keyless - uses OIDC identity)
signs:
  - id: archives
    cmd: cosign
    artifacts: archive
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
  - id: checksums
    cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"

# Generate Software Bill of Materials for archives
sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

# Docker Images - Using v2 format with multi-platform support
dockers_v2:
  - id: alpine
    dockerfile: Dockerfile.alpine
    ids:
      - kubefwd
    images:
      - txn2/kubefwd
    tags:
      - latest
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - latest_alpine-3
      - "{{ .Tag }}_alpine-3"
      - "v{{ .Major }}_alpine-3"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "{{ .GitURL }}"

  - id: ubuntu
    dockerfile: Dockerfile.ubuntu
    ids:
      - kubefwd
    images:
      - txn2/kubefwd
    tags:
      - latest_ubuntu-24.04
      - "{{ .Tag }}_ubuntu-24.04"
      - "v{{ .Major }}_ubuntu-24.04"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "{{ .GitURL }}"

# Sign Docker images with Cosign (keyless)
docker_signs:
  - cmd: cosign
    args:
      - "sign"
      - "--yes"
      - "${artifact}"
    artifacts: all

nfpms:
  - id: default
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://kubefwd.com
    description: Kubernetes bulk port forwarding utility.
    maintainer: Craig Johnston <cj@imti.co>
    license: Apache 2.0
    vendor: txn2
    formats:
      - apk
      - deb
      - rpm
    recommends:
      - kubectl

release:
  github:
    owner: txn2
    name: kubefwd
  name_template: "{{.ProjectName}}-v{{.Version}}"

# Homebrew Formula - for existing users who installed via `brew install txn2/tap/kubefwd`
brews:
  - name: kubefwd
    repository:
      owner: txn2
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Craig Johnston
      email: cj@imti.co
    directory: Formula
    homepage: https://kubefwd.com
    description: "Kubernetes bulk port forwarding utility."
    license: "Apache-2.0"
    dependencies:
      - name: kubectl
        type: optional
    test: |
      system "#{bin}/kubefwd version"
