coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 50%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
