FROM alpine:3

ARG TARGETPLATFORM

RUN apk update \
    && apk add --no-cache curl ca-certificates \
    && rm -rf /var/cache/apk/*

COPY ${TARGETPLATFORM}/kubefwd /kubefwd
WORKDIR /
ENTRYPOINT ["/kubefwd"]
