FROM alpine:3@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62

ARG TARGETPLATFORM

RUN apk update \
    && apk add --no-cache curl ca-certificates \
    && rm -rf /var/cache/apk/*

COPY ${TARGETPLATFORM}/kubefwd /kubefwd
WORKDIR /
ENTRYPOINT ["/kubefwd"]
