FROM ubuntu:24.04

ARG TARGETPLATFORM

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY ${TARGETPLATFORM}/kubefwd /kubefwd
WORKDIR /
ENTRYPOINT ["/kubefwd"]
