FROM alpine:3@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

ARG TARGETPLATFORM

RUN apk update \
    && apk add --no-cache curl ca-certificates \
    && rm -rf /var/cache/apk/*

COPY ${TARGETPLATFORM}/kubefwd /kubefwd
WORKDIR /
ENTRYPOINT ["/kubefwd"]
